name: Publish to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repository
        uses: actions/checkout@v4

      - name: Configure Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.70"

      - name: Install dependencies
        run: |
          pip install -e .
          pip install pytest

      - name: Run tests with pytest
        run: pytest

  publish:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4

      - name: Configure Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.70"

      - name: Install dependencies
        run: pip install build

      - name: Build the package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
